### PR TITLE
Add application metadata and a manpage

### PR DESCRIPTION
**Pull request by rafalcieslak**
A number of adjustments that should help package maintainers.

- Added a metainfo.xml file (#5)
- Adjusted .desktop file name to match app id (#5)
- Added a manpage (#6)

@musicinmybrain please let me know if this matches your expectations :slightly_smiling_face:

### CODE REVIEW

**Comment by musicinmybrain** [comment]
Thanks, this looks great to me, except for a couple of details!

Here’s what it looks like in GNOME Software Center:

harmonyseq-gnome-software

I see only two small issues:

1. The unordered list entry “chord management system which allows to easily organize melodies that sound great together” is split between two list entries, so there is a `</li>` and a `<li>` that need to be removed in the middle.
2. A generic icon is displayed. I’m not sure what’s going on there. I’ll try to look into it.

Also, with the desktop file renaming, the icon of the running application is now generic (the launcher, based on the desktop file, is fine). This looks like a variation on https://github.com/spyder-ide/spyder/issues/13786.

I’ll try to study the icon issues a bit more and follow up.

**Comment by musicinmybrain** [comment]
Oh, one more typo fix: `polyrythms` → `polyrhythms`, here and anywhere else it shows up.

**Comment by musicinmybrain** [comment]
Well, I haven’t figured out why the icon is not appearing in the GNOME Software Center. Maybe it will work once the package is in the Fedora repositories instead of just a local RPM install. It’s hard to debug. Not a dealbreaker, though.

For the running application icon under GNOME/Wayland, the [same fix Inkscape used](https://gitlab.com/inkscape/inkscape/-/issues/539) seems to work well:

```diff
diff -Naur harmonySEQ-0.17-original/src/main.cpp harmonySEQ-0.17/src/main.cpp
--- harmonySEQ-0.17-original/src/main.cpp	2020-03-04 08:48:23.000000000 -0500
+++ harmonySEQ-0.17/src/main.cpp	2021-04-25 08:41:47.832909900 -0400
@@ -209,6 +209,10 @@
     // Initialize GTK
     Gtk::Main gtk_main(argc, argv);
 
+    // For the icon to appear correctly on GNOME/Wayland, this needs to match
+    // the ID used in the AppStream XML and desktop files.
+    g_set_prgname("org.cielak.harmonyseq");
+
     // Initialize the MIDI driver...
     engine = new Engine();
 
```

That should probably be part of this PR, since it was working before the desktop file name change.

**Comment by rafalcieslak** [comment]
Thanks for your feedback, I think I've addressed all your remarks.

**Comment by musicinmybrain** [comment]
Looks reasonable to me! If I figure out anything else down the road, I’ll submit a PR. Thanks for adding these files.

**Pull request merged**
